FROM python

RUN apt update && apt upgrade -y \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt install python3.12 \
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12 \
    && python3 --verison

WORKDIR /var/LeazyPortfolio/src/

COPY requirements.txt ./
RUN pip3.12 install -r requirements.txt
COPY . .

EXPOSE 8000
CMD [ "python3", "manage.py", "runserver", "0.0.0.0:8000" ]




